name       : python-async_timeout
version    : 4.0.2
release    : 4
source     :
    - https://github.com/aio-libs/async-timeout/archive/refs/tags/v4.0.2.tar.gz : 1eb41fc35a0a24461b00f3479553972c99300e194eb212ff8b816c90c084d1d4
homepage   : https://github.com/aio-libs/async-timeout
license    : Apache-2.0
component  : programming.python
summary    : Timeout context manager for asyncio programs
description: |
    Timeout context manager for asyncio programs
build      : |
    %python3_setup
install    : |
    %python3_install
