name       : python-async_timeout
version    : 4.0.3
release    : 6
source     :
    - https://github.com/aio-libs/async-timeout/archive/refs/tags/v4.0.3.tar.gz : c63f1252d5fa878fdceb7a6894f1df6a73f92546e52a0b7999a5de429fd64ff8
homepage   : https://github.com/aio-libs/async-timeout
license    : Apache-2.0
component  : programming.python
summary    : Timeout context manager for asyncio programs
description: |
    Timeout context manager for asyncio programs
build      : |
    %python3_setup
install    : |
    %python3_install
