name       : python-async_timeout
version    : 3.0.1
release    : 2
source     :
    - https://github.com/aio-libs/async-timeout/archive/v3.0.1.tar.gz : d0a7a927ed6b922835e1b014dfcaa9982caccbb25131320582cc660af7c93949
license    : Apache-2.0
component  : programming.python
summary    : Timeout context manager for asyncio programs
description: |
    Timeout context manager for asyncio programs
build      : |
    %python3_setup
install    : |
    %python3_install
